### PR TITLE
Bumping dependencies and devDependencies

### PR DESCRIPTION
**Pull request by eklem**
Nice module, good if it is kept updated. The tests works
```console
oles-mbp-3:ndjson eklem$ npm test

> ndjson@1.5.1 test /Users/eklem/github_modules/ndjson
Bumping all dependencies
> tape test.js

TAP version 13
# .parse
ok 1 should be equal
# .parse twice
ok 2 should be equal
ok 3 should be equal
# .parse - strict:true error
ok 4 error thrown
# .parse - strict:true error event
ok 5 error event called
# .parse - strict:false error
ok 6 parse second one
# .serialize
ok 7 should be equal
# .serialize circular
ok 8 should be equal

1..8
# tests 8
# pass  8

# ok
```

### CODE REVIEW

**Comment by contra** [comment]
@eklem This project appears to be abandoned - I forked and updated everything + published on npm as `ndjson-next`

**Comment by eklem** [comment]
I think a lot of people dropped streaming interfaces, so it became less important.

**Comment by finnp** [comment]
@contra Thanks for that. I'm only a collaborator, so I can't add you to the repository. But if you want I can give you access to npm and you could continue publishing from the work.

**Comment by contra** [comment]
@finnp I can do that - if we want to go that route we should probably add a note in the README of this repo to go to the other repo. Let me know how you want to handle it - I'd love to keep it with the original owner if possible but I am happy to take ownership if they aren't around anymore.

**Comment by finnp** [comment]
@contra Cool, I added you as a collaborator to npm. I don't think @maxogden would mind continuing somewhere else. I could also add you to https://github.com/ndjson and we move the repository there.

**Comment by contra** [comment]
@finnp Yeah I can transfer my fork there and we can continue from that

**Comment by finnp** [comment]
@contra Okay, I invited you to the organization.  Let me know when you transferred the repository and I will make a note here that it has been moved.

**Comment by contra** [comment]
@finnp I get `You don’t have the permission to create public repositories on ndjson` when trying to transfer

**Comment by finnp** [comment]
@contra You haven't accepted the invitation to the org yet. Not sure where to do it but once you did it it should work

**Comment by contra** [comment]
Got it - moved to https://github.com/ndjson/ndjson.js if you want to put the note in the README, I'll cut a new major release on the ndjson package.

**Comment by eklem** [comment]
Closing this PR, cool the module got a new home :-)

**Pull request closed without merging**
